data_root:
  descriptors: "/media/vectr/T9/Dataset/overlap_transformer/descriptors"
#  gt_overlap: "/media/vectr/T9/Dataset/overlap_transformer/gt_overlap"
  gt_overlaps: "/media/vectr/T9/Dataset/overlap_transformer/gt_overlaps"
  keyframes: "/media/vectr/T9/Dataset/overlap_transformer/keyframes"
  npy_files: "/media/vectr/T9/Dataset/overlap_transformer/npy_files"
  overlaps: "/media/vectr/T9/Dataset/overlap_transformer/overlaps"
  pcd_files: "/media/vectr/T9/Dataset/overlap_transformer/pcd_files"
  png_files: "/media/vectr/T9/Dataset/overlap_transformer/png_files"
  poses: "/media/vectr/T9/Dataset/overlap_transformer/poses"
  test: "/media/vectr/T9/Dataset/overlap_transformer/test"
  weights: "/media/vectr/T9/Dataset/overlap_transformer/weights/weights_0.3"

seqs:
  all: ["bomb_shelter", "botanical_garden", "bruin_plaza", "court_of_sciences", "dickson_court", "geo_loop",
        "kerckhoff", "luskin", "royce_hall", "sculpture_garden"]
  train: ["bomb_shelter", "botanical_garden", "bruin_plaza", "court_of_sciences", "dickson_court", "kerckhoff"]
  valid: ["geo_loop"]

test_root:
  data_root_folder: "/media/vectr/T9/Dataset/overlap_transformer"
