data_root:
  pcd_files: "/media/vectr/T9/Dataset/overlap_transformer/pcd_files"
  npy_files: "/media/vectr/T9/Dataset/overlap_transformer/npy_files"
  poses: "/media/vectr/T9/Dataset/overlap_transformer/poses"
  weights: "/media/vectr/T9/Dataset/overlap_transformer/weights"

test_root:
  data_root_folder: "/media/vectr/T9/Dataset/overlap_transformer"