"lidar":
  "width": 512
  "height": 32
  "max_range_0.8": 75.0
  "max_range_0.1": 35.0
#  "fov_up": 22.5             # ucla_old, arl
#  "fov_down": -22.5
  "fov_up": 45.0              # ucla_new
  "fov_down": -45.0
  "overlap_thresh": 0.3
  "eps": 1.0e-5

"learning":
  "learning_rate": 5.0e-5
#  "learning_rate": 1.0e-4
  "learning_rate_overlap": 1.0e-4
  "num_pos_max": 30
  "num_pos_max_overlap": 20
  "num_neg_max": 30
  "num_neg_max_overlap": 10
  "num_epochs": 50
  "num_workers": 4

  "height": 32
  "width": 512
  "channels": 1
  "descriptor_size": 256
  "use_transformer": true

  "margin1": 0.15       # 0-2 in cosine, 0-4 in euclidean, 0.5 euclidean = (0.15~) 0.25 cosine, 1.0 euclidean = 0.5 cosine, 2.0 euclidean = 1.0 cosine
  "alpha": 0.0
  "metric": "cosine"    # cosine or euclidean
  "dist_thresh": 5.0    # threshold for euclidean distance test

"odom":
  maxCorrespondenceDistance: 0.5
  overlapThresh: 0.1

"test":
  "top_n": 5
