"lidar":
  "width": 900
  "height": 32
  "max_range_0.8": 75.0
  "max_range_0.1": 35.0
  "fov_up": 45.0
  "fov_down": -45.0
  "overlap_thresh": 0.3
  "eps": 1.0e-5

"odom":
  maxCorrespondenceDistance: 0.5
  overlapThresh: 0.1
