"lidar":
  "width": 900
  "height": 32
  "max_range_0.8": 75.0
  "max_range_0.1": 35.0
#  "fov_up": 22.5
#  "fov_down": -22.5
  "fov_up": 45.0
  "fov_down": -45.0
  "overlap_thresh": 0.3
  "eps": 1.0e-5

"learning":
  "learning_rate": 5.0e-5,
  "num_pos_max": 8,
  "num_neg_max": 8,
  "num_epochs": 50,
  "num_workers": 4,

  "height": 32,
  "width": 900,
  "channels": 1,
  "use_transformer": true,

  "margin1": 0.5

"odom":
  maxCorrespondenceDistance: 0.5
  overlapThresh: 0.1

"test":
  "top_n": 5
